import 'dart:core';

List<String> trMeslekler = [
  "Acil Durum ve Afet Yönetimi",
  "Asker",
  "Aşçı / Garson",
  "Avukat",
  "Bakkal / Market / Kasap / Manav",
  "Bankacı",
  "Barista",
  "Bekçi",
  "Berber / Kuaför / Güzellik Uzmanı",
  "Bilgi İşlem",
  "Bilgi Teknolojileri",
  "Biyolog",
  "Borsacı / Finansçı / Ekonomist",
  "Boyacı / Elektrikçi / Tesisatçı / Tamirci",
  "Çiftçi / Besici / Balıkçı / Ormancı",
  "Danışman",
  "Denetim",
  "Din Görevlisi",
  "Distribütör",
  "Diyetisyen",
  "Doktor / Diş Hekimi",
  "Eczacı",
  "Emlak / Gayrimenkul",
  "Esnaf",
  "E-ticaret",
  "Ev Hanımı",
  "Fizyoterapist",
  "Fotoğrafçı",
  "Gazeteci",
  "Girişimci",
  "Gümrük Müşaviri",
  "Güvenlik Görevlisi",
  "Hakim / Savcı",
  "Hemşire",
  "Hostes",
  "İdari İşler",
  "İnsan Kaynakları",
  "İş Geliştirme",
  "İşçi",
  "İşletmeci (Kafe, Otel, Restoran, Eğlence Merkezi)",
  "Kahve Kavurma",
  "Kamu Görevlisi",
  "Kuyumcu / Sarraf",
  "Lojistik",
  "Maliyet Kontrol",
  "Memur",
  "Menajer / Yapımcı / Yönetmen / Organizatör",
  "Mimar / İç Mimar",
  "Mobilyacı",
  "Muhasebeci / Mali Müşavir",
  "Müfettiş",
  "Mühendis",
  "Müteahhit",
  "Noter",
  "Öğrenci",
  "Öğretim Görevlisi / Akademisyen",
  "Öğretmen / Eğitmen",
  "Pazarlamacı",
  "Peyzaj",
  "Polis",
  "Programcı / Yazılımcı / Analist",
  "Psikolog",
  "Rehber / Tur operatörü",
  "Reklamcı",
  "Sağlık Hizmetleri",
  "Saha Koordinatörü",
  "Sanatçı (Yazar, Ressam, Ses, Film, Tiyatro)",
  "Satın Alma",
  "Satış Görevlisi  /  Tezgahtar",
  "Sekreter",
  "Sigortacı",
  "Sivil Pilot / Kaptan",
  "Sosyal Medya /  İçerik Yönetimi",
  "Sporcu / Antrenör / Hakem",
  "Şoför",
  "Tacir",
  "Tasarımcı (Grafik, Moda, Sanat, Reklam)",
  "Tekniker",
  "Teknisyen",
  "Tercüman / Çeviri Hizmetleri",
  "Turizm / Otelcilik",
  "Üretim",
  "Veteriner",
  "Yapımcı / Yönetmen",
  "Diğer",
];
